postgres:
    image: postgres
    ports:
    - "5432:5432"
    environment:
    - POSTGRES_DATABASE=keycloak
    - POSTGRES_USER=keycloak
    - POSTGRES_PASSWORD=keycloak

keycloak:
    image: jboss/keycloak-postgres:1.9.1.Final
    links:
    - postgres:postgres
    environment:
    - POSTGRES_DATABASE=keycloak
    - POSTGRES_USER=keycloak
    - POSTGRES_PASSWORD=keycloak
    - KEYCLOAK_USER=admin
    - KEYCLOAK_PASSWORD=admin
    ports:
    - 8080:8080
    - 8443:8443

xwiki:
    build: xwiki/
    ports:
    - 80:8080
    - 443:8443
    links:
    - keycloak:keycloak
#    - postgres:postgres
    environment:
    - KEYCLOAK_SERVER_URL

